#!/usr/bin/env python
import sys
import re
import os

for arg in sys.argv[1:]:
	with open(arg, "r") as fin:
		lines = fin.readlines()

	outf = os.path.basename(arg).split(".")
	outf = ".".join(outf[:-1]) + ".tsv"
	with open(outf, "w") as fout:
		print >>fout, "time\tfrequency\tsnr"
		for line in lines:
			if line[0] == "#":
				continue
			print >>fout, re.sub("\s", "\t", line)
