#!/usr/bin/env python
import sys
import json

def convert_summ_table(lines):
	summ = {}
	rounds = []
	for line in lines:
		if line[0] == "#": 
			continue
		print line
		round = {}
		round["round"], round["winner"], round["twind"], round["snr"], \
			round["sig"], round["nveto"], round["use"], round["eff"], round["dead"], \
			round["cum_eff"], round["cum_dead"] = line.split()
		round["ref_channel"] = "L1:OAF-CAL_DARM_DQ"
		# Sanitize channel name
		round["winner"] = "_".join(round["winner"].split("_")[:-1])
		round["winner"] = "L1:" + round["winner"]
		rounds.append(round)
	summ["rounds"] = rounds
	return summ

with open(sys.argv[1], "r") as fin:
	summ_table = fin.readlines()
rounds = convert_summ_table(summ_table)

rounds["base_url"] = "https://ldas-jobs.ligo-la.caltech.edu/~hveto/daily/201502/20150228/L1-omicron_BOTH-1109116816-28800-DARM/"

#rounds["ref_channel"] = "L1:OAF-CAL_DARM_DQ"
rounds["gps_start"] = 1109116816
rounds["gps_end"] = 1109116816 + 28800

with open("hveto.json", "w") as fout:
	json.dump(rounds, fout)
